### ISSUE TITLE
Fix teku to use `genesis-state` instead of `initial-state` for custom networks 

### ISSUE THREAD

**Issue by barnabasbusa** [ethpandaops/dencun-devnets#241]
Fix teku to use `genesis-state` instead of `initial-state` for custom networks 

https://github.com/Consensys/teku/issues/7643

**Comment by parithosh** [comment]
Ah cool, we should switch to this behavior for sure. So ansible-collection checkpointSync feature should be adding `initial-state`. We should be using `genesis-state` on all of our systems. So if we enable `checkpoint_sync: true`, then the `initial-state` would override the `genesis-state` flag we have set by default.

**Comment by barnabasbusa** [comment]
yup

**Comment by barnabasbusa** [comment]
Fixed as of devnet 11 going forward.
